//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace company
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSell
    {
        public int Id { get; set; }
        public int Quantity { get; set; }
        public string ItemNo { get; set; }
        public string Size { get; set; }
        public string NW { get; set; }
        public string GW { get; set; }
        public string Harber { get; set; }
        public string HarberCode { get; set; }
        public string OrderNo { get; set; }
        public string Po { get; set; }
        public int CDate { get; set; }
        public int Date { get; set; }
        public string Out { get; set; }
        public Nullable<int> Al { get; set; }
    }
}
